openapi: 3.0.0
info:
  title: CineView API
  version: "1.0"
  description: API para gestionar usuarios y reviews en CineView.

paths:
  /register:
    post:
      summary: Registro de usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "testuser"
                password:
                  type: string
                  example: "password123"
      responses:
        "201":
          description: Usuario creado correctamente
        "400":
          description: Nombre de usuario ya existe

  /login:
    post:
      summary: Inicio de sesión
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: "testuser"
                password:
                  type: string
                  example: "password123"
      responses:
        "200":
          description: Login exitoso
        "401":
          description: Nombre de usuario o contraseña incorrectos

  /add_review:
    post:
      summary: Añadir review
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 1
                movie_id:
                  type: integer
                  example: 101
                content:
                  type: string
                  example: "Great movie!"
      responses:
        "201":
          description: Reseña añadida exitosamente
        "400":
          description: Faltan datos necesarios (user_id, movie_id, content)
  /get_reviews_for_film_id:
    post:
      summary: Obtener todas las reseñas de una película por su ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                movie_id:
                  type: integer
                  example: 101
      responses:
        "200":
          description: Reseñas obtenidas exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  reviews:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: integer
                          example: 1
                        content:
                          type: string
                          example: "Great movie! I loved it."
                        created_at:
                          type: string
                          format: date-time
                          example: "2025-01-04T12:34:56"
        "400":
          description: Faltan datos necesarios (movie_id)
        "404":
          description: No se encontraron reseñas para esta película